import json
from pathlib import Path
from typing import Any, Dict, List, Optional
import joblib
import numpy as np
import pandas as pd

from document_validator import validate_all_documents


def _to_native(val):
    """Convert numpy scalar types to native Python types for JSON serialisation."""
    if isinstance(val, (np.integer,)):
        return int(val)
    if isinstance(val, (np.floating,)):
        return float(val)
    if isinstance(val, (np.bool_,)):
        return bool(val)
    if isinstance(val, (np.ndarray,)):
        return val.tolist()
    return val


BASE_DIR = Path(__file__).resolve().parent
MODEL_PATH = BASE_DIR / "loan_model.pkl"
DATASET_PATH = BASE_DIR / "loan_approval_dataset.csv"

_model = None


def get_or_train_model():
    global _model
    if _model is not None:
        return _model

    if MODEL_PATH.exists():
        _model = joblib.load(MODEL_PATH)
        return _model

    # Automatically train if missing
    import subprocess
    import sys
    print("Training loan model on the fly...")
    from train_model import train_model_pipeline
    _model = train_model_pipeline()
    return _model


def load_dataset():
    dataset = pd.read_csv(DATASET_PATH)
    dataset.columns = dataset.columns.str.strip()
    for column in dataset.select_dtypes(include=["object", "str"]).columns:
        dataset[column] = dataset[column].str.strip()
    return dataset


def generate_loan_processing_summary(
    application: Dict[str, Any],
    validation_result: Dict[str, Any],
    ml_result: Dict[str, Any],
    documents: List[Dict[str, Any]]
) -> str:
    """
    GenAI Loan Processing Summary & Audit Report.
    Generates a structured, executive review memo for the loan officer.
    """
    applicant_name = application.get("applicant_name", "Unknown Applicant")
    annual_income = float(application.get("annual_income") or 0.0)
    loan_amount = float(application.get("loan_amount") or 0.0)
    cibil_score = application.get("cibil_score", 750)
    loan_id = application.get("loan_id", "N/A")

    checklist = validation_result.get("checklist", {})
    inconsistencies = validation_result.get("inconsistencies", [])
    ml_prediction = ml_result.get("model_prediction", "Review")
    ml_confidence = ml_result.get("confidence", 0.0)

    # Document status breakdown
    docs_summary_lines = []
    for doc_type, info in checklist.items():
        icon = "✓ [VERIFIED]" if info.get("uploaded") else "✗ [MISSING]"
        docs_summary_lines.append(f"  • {icon} {doc_type}")

    # Issues breakdown
    issues_lines = []
    if not inconsistencies:
        issues_lines.append("  • None detected. All document data points match application declarations.")
    else:
        for iss in inconsistencies:
            severity = iss.get("severity", "MEDIUM")
            issues_lines.append(f"  • [{severity}] {iss.get('message')}")

    # Overall recommendation
    if ml_prediction.lower() == "approved" and validation_result.get("is_valid") and len(inconsistencies) == 0:
        recommendation = "RECOMMEND APPROVAL (Fast-Track Eligible)"
        decision_notes = "All mandatory documents verified with zero discrepancies. Kaggle ML risk model predicts approval with high statistical confidence."
    elif any(i.get("severity") == "HIGH" for i in inconsistencies):
        recommendation = "REQUIRE MANUAL REVIEW / ESCALATION"
        decision_notes = "Critical discrepancies or missing mandatory documents detected. Officer verification of identity or income documents required before underwriting."
    else:
        recommendation = "CONDITIONAL APPROVAL / OFFICER DISCRETION"
        decision_notes = "Minor variances observed. Review collateral valuations and bank statement balance before final sign-off."

    summary = f"""================================================================================
SMARTLOAN AI - GENAI LOAN PROCESSING SUMMARY & AUDIT MEMO
================================================================================
APPLICATION REFERENCE: {application.get('application_id', 'N/A')}
DATASET BENCHMARK ID : Loan #{loan_id}
APPLICANT NAME       : {applicant_name}
REQUESTED LOAN       : ₹{loan_amount:,.2f}
DECLARED INCOME      : ₹{annual_income:,.2f} (CIBIL Score: {cibil_score})
EVALUATION TIMESTAMP : Generated by SmartLoan AI Agent

1. DOCUMENT CHECKLIST & VERIFICATION:
{chr(10).join(docs_summary_lines)}

2. CROSS-DOCUMENT DISCREPANCIES & RED FLAGS:
{chr(10).join(issues_lines)}

3. KAGGLE ML PREDICTION & CREDIT ASSESSMENT:
  • Model Prediction   : {ml_prediction.upper()}
  • Model Confidence   : {ml_confidence:.1f}%
  • Underwriting Risk  : {ml_result.get('risk_level', 'Medium')} Risk
  • Financial Metrics  : CIBIL Score {cibil_score}, Loan-to-Income {(loan_amount/annual_income):.2f}x

4. AGENT DECISION & RECOMMENDED ACTION:
  • Verdict            : {recommendation}
  • Underwriter Notes  : {decision_notes}
================================================================================
"""
    return summary


def calculate_eligibility(
    annual_income,
    loan_amount,
    validation_result,
    applicant_name=None,
    loan_id=None,
    cibil_score=750,
    loan_term=10,
    education="Graduate",
    self_employed="No",
    residential_assets=0,
    commercial_assets=0,
    luxury_assets=0,
    bank_asset=0,
):
    """
    Predicts eligibility using the trained Random Forest model.
    """
    model = get_or_train_model()

    # If loan_id is in dataset, borrow matching profile fields if available
    record = None
    if loan_id:
        try:
            dataset = load_dataset()
            match = dataset[dataset["loan_id"] == int(loan_id)]
            if not match.empty:
                record = match.iloc[0]
        except Exception:
            pass

    if record is not None:
        no_of_dependents = int(_to_native(record["no_of_dependents"]))
        education = str(_to_native(record["education"])).strip()
        self_employed = str(_to_native(record["self_employed"])).strip()
        loan_term = int(_to_native(record["loan_term"]))
        cibil = int(_to_native(record["cibil_score"]))
        res_assets = float(_to_native(record["residential_assets_value"]))
        comm_assets = float(_to_native(record["commercial_assets_value"]))
        lux_assets = float(_to_native(record["luxury_assets_value"]))
        bk_asset = float(_to_native(record["bank_asset_value"]))
    else:
        no_of_dependents = 1
        cibil = cibil_score
        res_assets = residential_assets or (annual_income * 1.5)
        comm_assets = commercial_assets or 0
        lux_assets = luxury_assets or (annual_income * 0.8)
        bk_asset = bank_asset or (annual_income * 0.5)

    model_input = pd.DataFrame([{
        "no_of_dependents": no_of_dependents,
        "education": education,
        "self_employed": self_employed,
        "income_annum": float(annual_income),
        "loan_amount": float(loan_amount),
        "loan_term": loan_term,
        "cibil_score": cibil,
        "residential_assets_value": res_assets,
        "commercial_assets_value": comm_assets,
        "luxury_assets_value": lux_assets,
        "bank_asset_value": bk_asset,
    }])

    try:
        prediction = model.predict(model_input)[0]
        probabilities = model.predict_proba(model_input)[0]
        confidence = round(float(max(probabilities)) * 100, 2)
        prediction_text = str(prediction).strip()
    except Exception as e:
        print("ML prediction error:", e)
        prediction_text = "Approved" if cibil >= 650 else "Rejected"
        confidence = 85.0

    is_approved = prediction_text.lower() == "approved"
    doc_is_valid = validation_result.get("is_valid", True)
    has_high_issues = any(i.get("severity") == "HIGH" for i in validation_result.get("inconsistencies", []))

    if is_approved and doc_is_valid and not has_high_issues:
        status = "Approved"
        risk_level = "Low"
        reason = "Documents verified with no high-severity discrepancies, and Kaggle ML model confirms approval."
    elif not doc_is_valid or has_high_issues:
        status = "Manual Review"
        risk_level = "High"
        reason = "Documents contain discrepancies or missing mandatory proofs requiring officer verification."
    elif not is_approved:
        status = "Rejected"
        risk_level = "High"
        reason = "Application does not meet automated underwriting criteria based on ML credit scoring."
    else:
        status = "Manual Review"
        risk_level = "Medium"
        reason = "Borderline score or minor discrepancies detected. Officer discretion advised."

    return {
        "status": status,
        "eligible": (status == "Approved"),
        "risk_level": risk_level,
        "reason": reason,
        "applicant_name": applicant_name,
        "dataset_loan_id": int(loan_id) if loan_id else None,
        "model_prediction": prediction_text,
        "confidence": float(confidence),
        "cibil_score": int(cibil),
    }